#drums

grid:
  rows: 4
  cols: 4

camera:
  fps: 60
  index: 0

midi:
  trigger:
    threshold: 100  # The luminosity threshold for triggering notes (0-255)
  squares:
    - row: 0
      col: 0
      base_note: 36
      channel: 0
      color_scale_mapping: true
    - row: 0
      col: 1
      base_note: 39
      channel: 1
      color_scale_mapping: true
    - row: 0
      col: 2
      base_note: 42
      channel: 2
      color_scale_mapping: true
    - row: 0
      col: 3
      base_note: 45
      channel: 3
      color_scale_mapping: true
    - row: 1
      col: 0
      base_note: 49
      channel: 4
      color_scale_mapping: true
    - row: 1
      col: 1
      base_note: 51
      channel: 5
      color_scale_mapping: true
    - row: 1
      col: 2
      base_note: 55
      channel: 6
      color_scale_mapping: true
    - row: 1
      col: 3
      base_note: 58
      channel: 7
      color_scale_mapping: true
    - row: 2
      col: 0
      base_note: 65
      channel: 8
      color_scale_mapping: true
    - row: 2
      col: 1
      base_note: 63
      channel: 9
      color_scale_mapping: true
    - row: 2
      col: 2
      base_note: 69
      channel: 10
      color_scale_mapping: true
    - row: 2
      col: 3
      base_note: 62
      channel: 11
      color_scale_mapping: true
    - row: 3
      col: 0
      base_note: 71
      channel: 12
      color_scale_mapping: true
    - row: 3
      col: 1
      base_note: 70
      channel: 13
      color_scale_mapping: true
    - row: 3
      col: 2
      base_note: 55
      channel: 14
      color_scale_mapping: true
    - row: 3
      col: 3
      base_note: 81
      channel: 15
      color_scale_mapping: true
