grid:
  rows: 6
  cols: 6

camera:
  fps: 60
  index: 0

midi:
  trigger:
    threshold: 100
  squares:
    - row: 0
      col: 0
      base_note: 36
      channel: 0
      color_source_mapping: true
    - row: 1
      col: 0
      base_note: 38
      channel: 1
      color_source_mapping: true
    - row: 1
      col: 1
      base_note: 39
      channel: 2
      color_source_mapping: true
    - row: 0
      col: 1
      base_note: 41
      channel: 3
      color_source_mapping: true
    - row: 0
      col: 2
      base_note: 43
      channel: 4
      color_source_mapping: true
    - row: 0
      col: 3
      base_note: 44
      channel: 5
      color_source_mapping: true
    - row: 1
      col: 3
      base_note: 46
      channel: 6
      color_source_mapping: true
    - row: 1
      col: 2
      base_note: 48
      channel: 7
      color_source_mapping: true
    - row: 2
      col: 2
      base_note: 50
      channel: 8
      color_source_mapping: true
    - row: 2
      col: 1
      base_note: 51
      channel: 9
      color_source_mapping: true
    - row: 2
      col: 0
      base_note: 53
      channel: 10
      color_source_mapping: true
    - row: 3
      col: 0
      base_note: 55
      channel: 11
      color_source_mapping: true
    - row: 3
      col: 1
      base_note: 56
      channel: 12
      color_source_mapping: true
    - row: 3
      col: 2
      base_note: 58
      channel: 13
      color_source_mapping: true
    - row: 3
      col: 3
      base_note: 60
      channel: 14
      color_source_mapping: true
    - row: 2
      col: 3
      base_note: 62
      channel: 15
      color_source_mapping: true
    - row: 2
      col: 4
      base_note: 63
      channel: 16
      color_source_mapping: true
    - row: 1
      col: 4
      base_note: 65
      channel: 17
      color_source_mapping: true
    - row: 0
      col: 4
      base_note: 67
      channel: 18
      color_source_mapping: true
    - row: 0
      col: 5
      base_note: 68
      channel: 19
      color_source_mapping: true
    - row: 1
      col: 5
      base_note: 70
      channel: 20
      color_source_mapping: true
    - row: 2
      col: 5
      base_note: 72
      channel: 21
      color_source_mapping: true
    - row: 3
      col: 5
      base_note: 74
      channel: 22
      color_source_mapping: true
    - row: 3
      col: 4
      base_note: 75
      channel: 23
      color_source_mapping: true
    - row: 4
      col: 4
      base_note: 77
      channel: 24
      color_source_mapping: true
    - row: 4
      col: 3
      base_note: 79
      channel: 25
      color_source_mapping: true
    - row: 4
      col: 2
      base_note: 81
      channel: 26
      color_source_mapping: true
    - row: 4
      col: 1
      base_note: 82
      channel: 27
      color_source_mapping: true
    - row: 4
      col: 0
      base_note: 84
      channel: 28
      color_source_mapping: true
    - row: 5
      col: 0
      base_note: 86
      channel: 29
      color_source_mapping: true
    - row: 5
      col: 1
      base_note: 87
      channel: 30
      color_source_mapping: true
    - row: 5
      col: 2
      base_note: 89
      channel: 31
      color_source_mapping: true
    - row: 5
      col: 3
      base_note: 91
      channel: 32
      color_source_mapping: true
    - row: 5
      col: 4
      base_note: 92
      channel: 33
      color_source_mapping: true
    - row: 5
      col: 5
      base_note: 94
      channel: 34
      color_source_mapping: true
    - row: 4
      col: 5
      base_note: 96
      channel: 35
      color_source_mapping: true
